//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntersectionDBEntities : DbContext
    {
        public IntersectionDBEntities()
            : base("name=IntersectionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contragent> Contragent { get; set; }
        public virtual DbSet<DocGenerated> DocGenerated { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<Doc> Doc { get; set; }
    }
}
